# Generated by Django 5.0.4 on 2024-05-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_account',
            field=models.BooleanField(default=False),
        ),
    ]
