# Generated by Django 5.0.4 on 2024-04-29 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Staff', '0007_loantype_loandetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('adhar_number', models.CharField(max_length=15, unique=True)),
                ('pancard_number', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(upload_to='account_documents')),
                ('pancard_document', models.FileField(unique=True, upload_to='account_documents')),
                ('adarcard_document', models.FileField(unique=True, upload_to='account_documents')),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.accounttype')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.accountbranches')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
