# Generated by Django 5.0.4 on 2024-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
