# Generated by Django 5.0.4 on 2024-04-29 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_openaccount_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_want_to_credit', models.PositiveIntegerField()),
                ('amount_want_to_debit', models.PositiveIntegerField()),
                ('upi_pin', models.CharField(max_length=6)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.openaccount')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
