# Generated by Django 5.0.4 on 2024-04-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_rename_amount_want_to_credit_transaction_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaccount',
            name='total_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
