# Generated by Django 5.0.4 on 2024-04-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_openaccount_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaccount',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
