# Generated by Django 5.0.4 on 2024-05-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_loanapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapply',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
