# Generated by Django 5.0.4 on 2024-05-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_alter_loanapply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaccount',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
