# Generated by Django 5.0.4 on 2024-05-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_alter_openaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaccount',
            name='age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
