# Generated by Django 5.0.4 on 2024-05-03 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_openaccount_age'),
        ('Staff', '0007_loantype_loandetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.account'),
        ),
    ]
