# Generated by Django 5.0.4 on 2024-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_rename_account_number_transaction_your_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deposit_amount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdraw_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
