# Generated by Django 5.0.4 on 2024-05-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_rename_withdraw_account_number_transaction_transaction_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='upi_pin',
        ),
        migrations.AddField(
            model_name='openaccount',
            name='upi_pin',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
