# Generated by Django 5.0.4 on 2024-05-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_alter_loanapply_loanamount_loanrepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapply',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Fully Repaid', 'Fully Repaid')], default='Pending', max_length=20),
        ),
    ]
