# Generated by Django 5.0.4 on 2024-04-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_accountbranches_district_accountbranches_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcategory',
            old_name='account_type',
            new_name='account_category',
        ),
    ]
