# Generated by Django 5.0.4 on 2024-04-28 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_rename_account_type_accountcategory_account_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.accounttype'),
        ),
    ]
