# Generated by Django 5.0.4 on 2024-04-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0004_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Staff.accountcategory'),
        ),
    ]
