# Generated by Django 5.0.4 on 2024-04-29 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_remove_account_account_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=50)),
                ('loan_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.accountcategory')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.PositiveIntegerField()),
                ('required_document', models.CharField(choices=[('home document', 'Home Document'), ('property document', 'Property Document'), ('salary certificate', 'salary certificate'), ('no document needed', 'No Document Needed')], max_length=20)),
                ('how_apply', models.CharField(max_length=200)),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Staff.loantype')),
            ],
        ),
    ]
