# Generated by Django 5.0.4 on 2024-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0007_loantype_loandetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantype',
            name='loan_category',
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='required_document',
            field=models.CharField(choices=[('home document', 'Home Document'), ('property document', 'Property Document'), ('salary certificate', 'Salary Certificate'), ('no document needed', 'No Document Needed')], max_length=20),
        ),
    ]
