# Generated by Django 5.0.4 on 2024-05-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0009_accountbranches_has_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbranches',
            name='has_account',
        ),
    ]
