# Generated by Django 5.0.4 on 2024-05-07 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_alter_loanapply_status'),
        ('FinancialPlanningTools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='current_amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.openaccount'),
        ),
    ]
